name: "✋ WhyMeet Server - Continuous Deployment"

permissions:
  contents: read
  actions: write
  packages: write

on:
  workflow_dispatch:

jobs:
  build:
    name: "🔨 Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Mkdir logs"
        run: |
          mkdir -p logs
          touch logs/.gitkeep

      - name: "Configure Environment Variables"
        run: |
          echo "Copying Development Environment Variables"
          echo "${{ secrets.ENV_FILE_BASE64 }}" | base64 -d > .env

      - name: Upload Configuration Artifact
        uses: actions/upload-artifact@v6
        with:
          name: project-package
          path: .
          include-hidden-files: true

  deploy:
    name: "🚀 Deploy"
    uses: OxyFoo/CICD/.github/workflows/deploy-docker.yml@main
    needs: build
    secrets: inherit
    with:
      author: "oxyfoo"
      environment: "production"
      artifact-name: "project-package"
      docker-compose-file: "docker-compose.prod.yml"
      docker-requires: "oxyfoo-server-web.service"
      restore-on-failure: false
      health-check-timeout: 600

      setup-steps: |
        node -v

        # Create .env.prod for the server container (same as .env for now)
        cp .env .env.prod

        npm ci
        npx prisma generate
        npm run build

      test-steps: |
        npm run test
        npm run lint
